name: "release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    permissions:
      id-token: "write"
      contents: "read"
      attestations: "write"
      packages: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: "actions/checkout@v4"

      - uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: "docker/metadata-action@v5"
        id: "meta"
        with:
          images: "guppy0130/esp8266-dash-server"
          tags: |
            type=semver,pattern={{raw}}

      - name: "Build and push Docker image"
        id: "push"
        uses: "docker/build-push-action@v6"
        with:
          context: "."
          file: "./Containerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: "linux/amd64,linux/arm64"

      - name: "Generate artifact attestation"
        uses: "actions/attest-build-provenance@v1"
        with:
          subject-name: "docker.io/guppy0130/esp8266-dash-server"
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
